package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

    public M setId(java.lang.Integer id) {
        set("id", id);
        return (M) this;
    }

    public java.lang.Integer getId() {
        return getInt("id");
    }

    public M setTitle(java.lang.String title) {
        set("title", title);
        return (M) this;
    }

    public java.lang.String getTitle() {
        return getStr("title");
    }

    public M setContent(java.lang.String content) {
        set("content", content);
        return (M) this;
    }

    public java.lang.String getContent() {
        return getStr("content");
    }

    public M setType(Integer type) {
        set("type", type);
        return (M) this;
    }

    public Integer getType() {
        return getInt("type");
    }

    public M setCreateTime(Date date) {
        set("create_time", date);
        return (M) this;
    }

    public Date getCreateTime() {
        return getDate("create_time");
    }

    public M setUpdateTime(Date date) {
        set("update_time", date);
        return (M) this;
    }

    public Date getUpdateTime() {
        return getDate("update_time");
    }
}
